version: '3.8'

services:
  mongodb:
    image: mongo:6.0.4-jammy
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
  app:
    depends_on:
      - mongodb
    build: .
    ports:
      - '8000:8000'
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin123
      - MONGO_DATABASE=library
    volumes:
      - ..:/home/pyhton/app:cached
